### ISSUE TITLE
线上bug及常见问题

### ISSUE THREAD

**Issue by usernameddd** [wsdo/recording#2]
1、必须本机访问（127.0.0.1/localhost）或者访问地址必须是https开头才能调用系统的音频函数，才能正常录音
2、在线demo只能进行一轮开始录音和停止录音，到第二轮的时候会报错，是因为在clearRecordedData()函数中的leftChannel = rightChannel = [];导致的，因为这样它们指向的就是同一个对象引用，当leftChannel进行push操作时，rightChannel也会变化。所以会导致leftChannel和rightChannel的长度翻倍，从而在mergeBuffers()函数中的result.set(buffer, offset);的时候会报错。
解决办法是：clearRecordedData()函数中将leftChannel = rightChannel = []; 变成 leftChannel = []; 
  rightChannel  = [];

**Comment by wsdo** [comment]
兼容性呢？
